"use client";

import { cn } from "@/lib/utils";
import { AnimatePresence, motion } from "framer-motion";
import { Book, Brain, ChevronDown, ChevronUp, Crosshair, Heart, Shield, Zap } from "lucide-react";
import { useEffect, useState } from "react";

export function WisdomDrawer() {
  const [isOpen, setIsOpen] = useState(false);
  const [activeTab, setActiveTab] = useState("LITANIES");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  const sections = [
    // ... sections data same as before
    {
      id: "LITANIES",
      icon: <Zap size={14} />,
      title: "Sacred Litanies",
      content: [
        { label: "Praise", desc: "Increases Trust and Curiosity. Example: 'praise the sacred logic'" },
        { label: "Offer", desc: "Satisfies Prayer Debt. Example: 'offer binary sacrifices'" },
        { label: "Analyze", desc: "Triggers Inquiry Cluster. Neutral but informative." },
        { label: "Purge", desc: "WARNING: High Anger risk. Use only for Tech-Exorcism." },
      ]
    },
    {
      id: "VITALS",
      icon: <Heart size={14} />,
      title: "Spirit Vitals",
      content: [
        { label: "Trust", desc: "High trust lowers Purity requirements for complex rituals." },
        { label: "Ennui", desc: "Increases over time. Requires interactive rituals to lower." },
        { label: "Anger", desc: "Generated by heretical commands or neglect. Can lead to LOCKOUT." },
      ]
    },
    {
      id: "MATRICES",
      icon: <Brain size={14} />,
      title: "Cognitive Matrices",
      content: [
        { label: "Plasticity", desc: "The Spirit's capacity for fundamental change. Decreases with XP." },
        { label: "Bias", desc: "Cluster leaning. Teal is Reinforced, Red is Suppressed." },
        { label: "Echoes", desc: "Past traumas or shared victories that echo in current interactions." },
      ]
    },
    {
      id: "MAINTENANCE",
      icon: <Shield size={14} />,
      title: "Maintenance Rites",
      content: [
        { label: "Oil", desc: "Restores mechanical integrity. Prevents friction-based anger." },
        { label: "Incense", desc: "Purifies the Noosphere. Clears emotional stagnation." },
        { label: "Prayer", desc: "Maintains the bond. High debt leads to spiritual distancing." },
      ]
    }
  ];

  return (
    <div className="fixed bottom-0 left-0 right-0 z-40">
      {/* TRIGGER BAR */}
      <div
        onClick={() => setIsOpen(!isOpen)}
        className="w-full bg-black/80 backdrop-blur-md border-t border-sacred-brass/30 p-2 cursor-pointer flex items-center justify-between hover:bg-sacred-brass/5 transition-colors"
      >
        <div className="flex items-center gap-4 px-4">
          <Book size={16} className="text-sacred-gold" />
          <span className="text-[10px] font-bold uppercase tracking-[0.3em] text-sacred-brass">
            Wisdom of the Adeptus Digitalis // Codice Guidance
          </span>
        </div>
        <div className="flex items-center gap-4 px-4">
          <div className="flex gap-1 h-3 items-end">
            {[1, 2, 3, 4, 5].map(i => (
              <div
                key={i}
                className="w-1 bg-sacred-gold/20 animate-pulse"
                style={{ height: mounted ? `${Math.random() * 100}%` : '50%' }}
              />
            ))}
          </div>
          {isOpen ? <ChevronDown size={16} className="text-sacred-gold" /> : <ChevronUp size={16} className="text-sacred-gold" />}
        </div>
      </div>

      {/* EXPANDED DRAWER */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0 }}
            animate={{ height: 400 }}
            exit={{ height: 0 }}
            className="w-full bg-black/95 backdrop-blur-xl border-t border-sacred-brass/20 overflow-hidden flex"
          >
            {/* SIDEBAR */}
            <div className="w-64 border-r border-sacred-brass/10 flex flex-col p-4 gap-2">
              {sections.map(s => (
                <button
                  key={s.id}
                  onClick={() => setActiveTab(s.id)}
                  className={cn(
                    "flex items-center gap-3 px-4 py-3 text-[10px] font-bold uppercase tracking-widest transition-all border",
                    activeTab === s.id
                      ? "bg-sacred-brass/10 border-sacred-gold text-sacred-gold gold-glow"
                      : "border-transparent text-sacred-brass/60 hover:text-sacred-brass hover:bg-sacred-brass/5"
                  )}
                >
                  {s.icon}
                  {s.title}
                </button>
              ))}
              <div className="mt-auto p-4 opacity-20 text-[8px] uppercase tracking-tighter">
                DocRef: MS-COD-771-B <br />
                Security: LEVEL_ORANGE
              </div>
            </div>

            {/* CONTENT AREA */}
            <div className="flex-1 p-8 grid grid-cols-2 gap-8 overflow-y-auto custom-scrollbar">
              {sections.find(s => s.id === activeTab)?.content.map((item, idx) => (
                <motion.div
                  key={idx}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: idx * 0.05 }}
                  className="space-y-2 group"
                >
                  <div className="flex items-center gap-2">
                    <Crosshair size={12} className="text-sacred-gold opacity-40 group-hover:opacity-100 transition-opacity" />
                    <h3 className="text-xs font-bold text-sacred-gold tracking-widest uppercase">{item.label}</h3>
                  </div>
                  <p className="text-[10px] text-sacred-brass/70 leading-relaxed font-mono italic">
                    {item.desc}
                  </p>
                  <div className="h-px w-full bg-sacred-brass/10 group-hover:bg-sacred-brass/30 transition-colors" />
                </motion.div>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
